name: login_signup_screen
description: Login and SignUp Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  adaptive_dialog: null
  agora_rtc_engine: ^4.0.6
  agora_rtm: ^0.9.14
  algorand_dart: ^0.0.2-beta.6
  awesome_dialog: null
  babstrap_settings_screen: ^0.1.0
  cached_network_image: null
  clay_containers: ^0.3.2
  cloud_firestore: ^2.4.0
  collapsible_sidebar: ^2.0.1
  cupertino_icons: ^1.0.0
  date_format: null
  emoji_picker_flutter: null
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.0
  firebase_storage: ^10.0.1
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_slidable: ^0.6.0
  flutter_svg: null
  flutter_vector_icons: ^1.0.0
  focused_menu: ^1.0.5
  font_awesome_flutter: 8.8.1
  geocoder: ^0.2.1
  get: ^4.3.0
  get_storage: ^2.0.3
  giphy_get: ^2.0.2
  google_nav_bar: ^5.0.5
  hive: ^1.4.1+1
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  linkify_text: null
  liquid_pull_to_refresh: ^3.0.0
  location: ^4.2.2
  new_gradient_app_bar: null
  permission_handler: 3.0.0
  photo_view: ^0.10.2
  pinput: ^1.2.2
  pretty_qr_code: ^2.0.2
  qr_code_scanner: ^0.5.2
  random_color: ^1.0.5
  scaled_list: ^1.0.1+6
  shimmer: null
  swipe_to: null
  timeago: null
  transparent_image: null
  wakelock: ^0.4.0
  webview_flutter: ^2.0.7

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/algo2.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/background.png
    - assets/welcome.png
    - assets/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AvenirNext-UltraLight
      fonts:
        - asset: assets/fonts/avenir/AvenirNext-UltraLight.ttf
          weight: 200
    - family: AvenirNext-Regular
      fonts:
        - asset: assets/fonts/avenir/AvenirNext-Regular.ttf
          weight: 400
    - family: AvenirNext-Medium
      fonts:
        - asset: assets/fonts/avenir/AvenirNext-Medium.ttf
          weight: 500
    - family: AvenirNext-DemiBold
      fonts:
        - asset: assets/fonts/avenir/AvenirNext-DemiBold.ttf
          weight: 600
    - family: AvenirNext-Bold
      fonts:
        - asset: assets/fonts/avenir/AvenirNext-Bold.ttf
          weight: 800
    - family: AvenirNext-Heavy
      fonts:
        - asset: assets/fonts/avenir/AvenirNext-Heavy.ttf
          weight: 900
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
